services:
  - type: web
    name: bohri-calendar
    env: python
    buildCommand: ./build.sh
    startCommand: python app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
    healthCheckPath: /api/health